/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// User and Profile types
export interface User {
  id: string;
  email: string;
  passwordHash: string;
  name: string;
}

export interface Profile {
  userId: string;
  education: string;
  skillLevel: 'beginner' | 'intermediate' | 'advanced';
  learningGoal: string;
  avatarUrl: string;
}

// Roadmap and Module types
export interface Roadmap {
  id: string;
  userId: string;
  topic: string;
  title: string;
  description: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced' | 'all';
  estimatedDuration: string;
  createdAt: string;
  progress: number; // percentage 0-100
  modules: RoadmapModule[];
}

export interface RoadmapModule {
  id: string;
  roadmapId: string;
  title: string;
  description: string;
  orderIndex: number;
  lessons: CompactLesson[];
}

export interface CompactLesson {
  id: string;
  moduleId: string;
  title: string;
  orderIndex: number;
  isCompleted: boolean;
}

// Detailed Lesson content (fully generated by AI)
export interface CodeExample {
  language: string;
  code: string;
  explanation: string;
}

export interface DetailedLesson {
  id: string;
  roadmapId: string;
  moduleId: string;
  title: string;
  explanation: string;
  keyConcepts: string[];
  keyPoints: string[];
  realWorldExamples: string[];
  codeExamples: CodeExample[];
  bestPractices: string[];
  commonMistakes: string[];
  summary: string;
  revisionNotes: string;
  interviewQuestions: string[];
}

// Detailed Notes content (fully generated by AI)
export interface FAQItem {
  question: string;
  answer: string;
}

export interface DetailedNotes {
  id: string;
  lessonId: string;
  title: string;
  definitions: { term: string; definition: string }[];
  detailedExplanation: string;
  examples: string[];
  importantPoints: string[];
  revisionNotes: string;
  interviewQuestions: string[];
  faq: FAQItem[];
}

// Quiz types
export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctOptionIndex: number;
  explanation: string;
}

export interface QuizAttempt {
  id: string;
  userId: string;
  roadmapId: string;
  moduleId: string;
  lessonId: string;
  correctCount: number;
  wrongCount: number;
  accuracy: number; // percentage 0-100
  timeSeconds: number;
  scorePercentage: number;
  completedAt: string;
}

// Coding Practice types
export interface CodingProblem {
  id: string;
  roadmapId: string;
  title: string;
  problemStatement: string;
  difficulty: 'beginner' | 'easy' | 'medium' | 'hard' | 'advanced';
  inputFormat: string;
  outputFormat: string;
  constraints: string[];
  examples: { input: string; output: string; explanation?: string }[];
  hints: string[];
  testCases: { input: string; expectedOutput: string; isHidden: boolean }[];
  explanation: string;
  sampleInput?: string;
  sampleOutput?: string;
}

export interface CodingAttempt {
  id: string;
  userId: string;
  problemId: string;
  code: string;
  language: string;
  status: 'success' | 'fail' | 'skipped';
  output: string;
  error?: string;
  completedAt: string;
  timeSpentSeconds?: number;
  difficulty?: 'beginner' | 'easy' | 'medium' | 'hard' | 'advanced';
}

// Bookmark types
export interface Bookmark {
  id: string;
  userId: string;
  type: 'roadmap' | 'lesson' | 'note' | 'coding' | 'quiz_question';
  targetId: string;
  title: string;
  subtitle: string;
  createdAt: string;
}

// Recommendation types
export interface Recommendation {
  id: string;
  userId: string;
  topic: string;
  type: 'roadmap' | 'lesson' | 'practice' | 'quiz';
  targetId?: string; // Empty if it suggests a new roadmap topic
  reason: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  createdAt: string;
}

// Streak types
export interface Streak {
  userId: string;
  currentStreak: number;
  longestStreak: number;
  lastActiveDate: string; // YYYY-MM-DD
  history: { [date: string]: boolean }; // Map YYYY-MM-DD to boolean
}

// Study Session types
export interface StudySession {
  id: string;
  userId: string;
  date: string; // YYYY-MM-DD
  durationSeconds: number;
  activityType: 'lesson' | 'quiz' | 'coding' | 'general';
}

// Notification and Activity log types
export interface Notification {
  id: string;
  userId: string;
  title: string;
  message: string;
  type: 'streak' | 'achievement' | 'system' | 'roadmap';
  read: boolean;
  createdAt: string;
}

export interface ActivityLog {
  id: string;
  userId: string;
  action: string;
  details: string;
  createdAt: string;
}

// Analytics and Dashboard statistics types
export interface AnalyticsData {
  lessonsCompleted: number;
  lessonsRemaining: number;
  roadmapProgress: number; // avg progress of active roadmaps
  quizAccuracy: number;
  codingAccuracy: number;
  averageQuizScore: number;
  averageCodingScore: number;
  studyTimeDaily: { date: string; minutes: number }[];
  studyTimeWeekly: { week: string; minutes: number }[];
  studyTimeMonthly: { month: string; minutes: number }[];
  strongTopics: string[];
  weakTopics: string[];
}
